### PR TITLE
support for non standard baud rates

### PR DESCRIPTION
**Pull request by azplanlos**
set baud rate via ioctl if normal attribute setting failes in order to support non-standard baud rates

### CODE REVIEW

**Comment by armadsen** [comment]
Hi Andreas, thanks for the pull request! There's actually already an active pull request for this feature, along with some discussion here: https://github.com/armadsen/ORSSerialPort/pull/45 .

The thing I like about your approach is that you leave the existing `termios`/`tcsetattr()` in place, only falling back to `ioctl()` in case that fails.

However, looking at your pull request, I have a few concerns:

- I'd like for the changes to be limited to supporting this feature.
- Is there a reason you removed the `NS_DESIGNATED_INITIALIZER` annotation on `-initWithDevice:`? That should be left there unless there's a good justification for removing it.
- Why are you #defining `IOSSIOSPEED` inside of ORSSerialPort? That's defined in <IOKit/ioss.h>, and should be imported from there if necessary.
- There's no error handling for the case where setting the baudrate with `ioctl()` as there is with the original call to `tcsetattr()`

Relevant to the discussion in the other pull request, have you tested this, and if so, with what kind of USB to serial adapters, and at what baud rates? 

Thanks!
Andrew

**Comment by azplanlos** [comment]
Hi Andrew,

to be honest, I just changed the code quick and dirty to solve a connection problem a had for a couple of weeks with a specific device. As it was working I filed the pull request.

If you are interested in a merge of this code, I could tidy it up and file another pull request.

This code is tested and working without issues so far. I am using a Junsi iCharger device which has a built in CP210x USB to serial adapter at a fixed baud rate of 128000 baud. Working perfect.

According to your remarks:

- you are right, this should be just a fall back when setting the baud rate the "normal way" fails. That is how I tried to design it.
- I removed the NS_DESIGNATED_INITIALIZER annotation so the code compiles on my OS X 10.7. There is no other issue with Lion at the moment except this. I thought, why shouldn't it work on an older system as well? I hate when new apps only target the newest OS ;-)
- IOSSIOSPEED should indeed be defined somewhere else outside the function code
- In the version I used before there was no real error handling anyway, except a NSLog, which in my opinion is more a debug info than real error handling. How are errors handled in ORSSerial? Should be treated the same way here I guess.

Let me know if you need me to do some changes in this code.

Best regards and thanks for discussing with me

Andreas

**Comment by armadsen** [comment]
Thanks Andreas,

> I removed the NS_DESIGNATED_INITIALIZER annotation so the code compiles on my OS X 10.7. There is no other issue with Lion at the moment except this. I thought, why shouldn't it work on an older system as well? I hate when new apps only target the newest OS ;-)
Nice catch. ORSSerialPort is actually supposed to support deployment back to 10.6. I've never made a promise about _compiling_ on older versions, but as long as this is the only thing preventing that, I'm OK with removing it for now. I would like to keep PRs/changesets clean, so this should be in a separate PR (or just make an issue, and I can do it).

> In the version I used before there was no real error handling anyway, except a NSLog, which in my opinion is more a debug info than real error handling. How are errors handled in ORSSerial? Should be treated the same way here I guess.

For now an NSLog() is fine. You'll note a TODO in the code to do real error handling here. For ORSSerialPort, that really just means calling the delegate's `-serialPort:didEncounterError:` method. ORSSerialPort has a (internal) `-notifyDelegateOfPosixError` method that can be used to easily do this. You can see how it's used several other places in the code. I'm fine with including this in your PR, but it could also be deferred for later.

Not directly mentioned in my first reply is the changes to the framework project file in your PR. Were those changes necessary to build on Lion? As with the NS_DESIGNATED_INITIALIZER change, I'd still rather them not be in this PR.

A new or updated pull request with the changes discussed here would be very much appreciated.

Thanks!
Andrew

**Comment by azplanlos** [comment]
created a new pull request #49 for this issue as discussed here

**Pull request closed without merging**
